#!/usr/bin/env bash

export VAGRANT_DEFAULT_PROVIDER="vmware_fusion"

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source box_common

  box_main "$@"
}

source sub "$BASH_SOURCE" "$@"
