#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- $(aws regions)
  fi

  runmany 10 'sleep $(( RANDOM % 60 ));  aws with $1 aws build 2>&1 | tee box-aws-$1.log' "$@"
}

set -efu
source sub "$BASH_SOURCE" "$@"
