#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export VAGRANT_CWD="$shome"

  case "${1:-}" in
    build|rebuild)
      (cd $APP_PATH/basebox-osx && vmware "$@")
      ;;

    *)
      vmware "$@"
      ;;
  esac
}

source sub "$BASH_SOURCE" "$@"
