#!/usr/bin/env bash

function fga_main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export VAGRANT_CWD="$shome"

  if [[ "$#" == 0 ]]; then
    echo "$(basename "$0"): up|destroy ssh|rsync|scp id media rebuild build|remove"
    return 0
  fi

  local nm_action="$1"; shift
  case "$VAGRANT_DEFAULT_PROVIDER" in
    vmware_fusion)
      local nm_guest='osx'
      local cmd_guest='fga osx'
      local nm_basebox_build='osx'
      local nm_rebuilder='vmware'
      local basebox_type='vmx'
      ;;
    virtualbox)
      local nm_guest='fga'
      local cmd_guest='fga'
      local nm_basebox_build='ubuntu'
      local nm_rebuilder='virtualbox'
      local basebox_type='ovf'
      ;;
  esac

  case "$nm_action" in
    up)
      parity "$nm_action" "$nm_guest" "$@"
      ;;
    destroy)
      vagrant "$nm_action" "$nm_guest" "$@"
      ;;
    ssh|rsync|scp)
      parity "$nm_action" "$nm_guest" "$@"
      ;;
    media)
      (cd "$APP_PATH/basebox-${nm_basebox_build}" && "$nm_rebuilder" build "$nm_basebox_build")
      $nm_rebuilder remove 2>&- || true
      $nm_rebuilder add 
      ;;
    export)
      case "$nm_rebuilder" in
        virtualbox)
          $cmd_guest ssh sudo passwd -u ubuntu
          { echo ubuntu; echo ubuntu; } | $cmd_guest ssh sudo passwd ubuntu
          $cmd_guest ssh sudo rm -rf /dev/.udev
          $cmd_guest ssh sudo rm -f /lib/udev/rules.d/75-persistent-net-generator.rules
          $cmd_guest ssh sudo rm -rf /var/lib/dhcp # TODO assumes only leases are here
          $cmd_guest ssh sudo mkdir -p /var/lib/dhcp
          $cmd_guest halt

          rm -f "${BASEBOX_CACHE}/box/vagrant.ovf" "${BASEBOX_CACHE}/box/vagrant-disk1.vmdk"
          VBoxManage export $(fga id) --ovf20 -o ${BASEBOX_CACHE}/box/vagrant.ovf
          ;;

        vmware)
          { echo ubuntu; echo ubuntu; } | $cmd_guest ssh sudo passwd ubuntu
          $cmd_guest halt
          ;;
      esac
      ;;
    rebuild)
      $nm_rebuilder build "$nm_basebox_build" "$basebox_type" "$($cmd_guest id)"
      $cmd_guest destroy -f
      $nm_rebuilder remove >/dev/null 2>&1 || true
      $nm_rebuilder add

      rm -f "$shome/cidata/meta-data"
      (cd $shome && make)
      $cmd_guest up
      ;;
    remove)
      $0 destroy -f
      ;;
    build)
      $0 up
      ;;
    id)
      cat "$(set +f; ls -td "$VAGRANT_CWD/.vagrant/machines/$nm_guest"/*/id | head -1)"; echo
      ;;
    *)
      vagrant "$nm_action" "$nm_guest" "$@"
      ;;
  esac
}
