#!/usr/bin/env bash

function fga_main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export VAGRANT_CWD="$shome"

  if [[ "$#" == 0 ]]; then
    echo "$(basename "$0"): up|destroy ssh|rsync|scp id media rebuild build|remove"
    return 0
  fi

  local nm_action="$1"; shift
  case "$VAGRANT_DEFAULT_PROVIDER" in
    vmware_fusion)
      local nm_guest='osx'
      local nm_basebox_build='osx'
      local nm_rebuilder='vmware'
      ;;
    virtualbox)
      local nm_guest='fga'
      local nm_basebox_build='ubuntu'
      local nm_rebuilder='virtualbox'
      ;;
  esac

  case "$nm_action" in
    up)
      parity "$nm_action" "$nm_guest" "$@"
      ;;
    destroy)
      vagrant "$nm_action" "$nm_guest" "$@"
      ;;
    ssh|rsync|scp)
      parity "$nm_action" "$nm_guest" "$@"
      ;;
    media)
      (cd "$APP_PATH/basebox-${nm_basebox_build}" && "$nm_rebuilder" build "$nm_basebox_build")
      $nm_rebuilder remove 2>&- || true
      $nm_rebuilder add 
      ;;
    export)
      { echo ubuntu; echo ubuntu; } | $nm_guest ssh sudo passwd ubuntu
      VBoxManage export $(fga id) --ovf20 -o ${BASEBOX_CACHE}/box/vagrant.ovf
      ;;
    rebuild)
      $0 remove >/dev/null 2>&1 || true
      $0 build
      ;;
    remove)
      $0 destroy -f
      ;;
    build)
      $0 up
      ;;
    id)
      cat "$(set +f; ls -td "$VAGRANT_CWD/.vagrant/machines/$nm_guest"/*/id | head -1)"; echo
      ;;
    *)
      vagrant "$nm_action" "$nm_guest" "$@"
      ;;
  esac
}
