#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  docker commit "$(limbo id)" "${BASEBOX_NAME}:vagrant"
}

source sub "$BASH_SOURCE" "$@"

