#!/usr/bin/env bash

function limbo_media_add {
  basebox remove || true
  basebox add
}

function limbo_media_prep {
  vagrant destroy -f
}

function source_id {
  ls -d ~/Documents/Parallels/$(prlctl list "$(limbo id)" | tail +2 | awk '{print $4}').pvm 2>/dev/null | awk '{print $1}' || true
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"
  if [[ -n "$nm_export" ]]; then
    shift
  fi

  export BASEBOX_SOURCE="$(source_id)"
  prlctl unregister "$(limbo id)"

  set -- "$basebox_type" "$nm_export" "$@"
  basebox build "$@"
  limbo_media_prep
  limbo_media_add
}

source sub "$BASH_SOURCE" "$@"
