#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  export VAGRANT_DEFAULT_PROVIDER='docker'

  exec limbo "$@"
}

source sub "$BASH_SOURCE" "$@"
