#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  local nm_provider="$1"; shift
  case "$nm_provider" in
    vmware*)
      env LIMBO_FAKE=1 limbo destroy -f
      $cmd_basebox build
      $cmd_basebox remove -f 2>&- || true
      $cmd_basebox add
      ;;
  esac
}

source sub "$BASH_SOURCE" "$VAGRANT_DEFAULT_PROVIDER" "$@"

