#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  eval $(docker machine env --swarm --no-proxy $BASEBOX_INSTANCE)

  exec docker run -ti -u ubuntu -w /home/ubuntu "$@"
}

source sub "$BASH_SOURCE" "$@"
