#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  if [[ "$#" == 0 ]]; then
    local pth_packages="${CACHE_DIR}/packages/"$(echo "$(parity ssh "$BASEBOX_NAME" uname -s)_$(parity ssh "$BASEBOX_NAME" uname -r | cut -d- -f1 | cut -d. -f1-3)${PKG_HOME}" | tr / _ | tr . _ | perl -pe 's{__+}{_}')""
    set -- "$pth_packages"
  fi

  for pth_packages in "$@"; do
    parity "ssh" "$BASEBOX_NAME" sudo install -d -o ubuntu -g ubuntu "$pth_packages"
    parity "rsync" "$BASEBOX_NAME" -ia --delete --progress "$pth_packages/." "${BASEBOX_NAME}:$pth_packages/"
  done
}

source sub-chain "$BASH_SOURCE" "$@"

