#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  env LIMBO_FAKE=1 limbo destroy -f
  basebox build "$@"
  basebox remove -f || true
  basebox add
}

source sub "$BASH_SOURCE" "$@"

