#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  eval $(docker machine env --swarm --no-proxy $BASEBOX_INSTANCE)

  exec "${BASEBOX_INSTANCE}" docker run -ti -u ubuntu -w /home/ubuntu "$@" bash -il
}

source sub "$BASH_SOURCE" "$@"
