#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

   cat "$(set +f; ls -td "$VAGRANT_CWD/.vagrant/machines/$BASEBOX_NAME"/*/id | head -1)"; echo
}

source sub-chain "$BASH_SOURCE" "$@"

