#!/usr/bin/env bash

unset http_proxy https_proxy

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  export LXD_CONF="$shome/.lxc/$BASEBOX_INSTANCE" 
  mkdir -p "$LXD_CONF"

  exec lxc "$@"
}

source sub "$BASH_SOURCE" "$@"
