#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local nm_import="${1:-}"
  local nm_suffix="${nm_import:+-${nm_import}}"

  basebox remove || true
  basebox add
}

source sub "$BASH_SOURCE" "$@"

