#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"

  export BASEBOX_SOURCE="${BASEBOX_NAME}:vagrant"
  export BASEBOX_TAG="vagrant"
  basebox build "$@"
  docker save -o "${CACHE_DIR}/box/${BASEBOX_NAME}${nm_suffix}.docker" "$BASEBOX_SOURCE"
}

source sub-chain "$BASH_SOURCE" "$@"

