#!/usr/bin/env bash

function source_id {
  limbo id
}

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"

  export BASEBOX_SOURCE="$(source_id)"

  set -- "$basebox_type" "$nm_export" "$@"
  basebox build "$@"
  limbo destroy -f
  basebox remove -f 2>&- || true
  basebox add

  rm -f "$shome/cidata/meta-data"
  (cd $shome && make)
}

source sub-chain "$BASH_SOURCE" "$@"

