#!/usr/bin/env bash

export VAGRANT_DEFAULT_PROVIDER='docker'

eval $(docker machine env --no-proxy $BASEBOX_INSTANCE)

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  exec docker "$@"
}

source sub "$BASH_SOURCE" "$@"
