#!/usr/bin/env bash

function limbo_update {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      sudo route add -net "${BASEBOX_DOCKER_NETWORK_PREFIX}.0" "${BASEBOX_IP}" 255.255.255.0
      sudo route add -net "${BASEBOX_LXD_NETWORK_PREFIX}.0"    "${BASEBOX_IP}" 255.255.255.0
      ;;
    Linux)
      sudo route add -net "${BASEBOX_DOCKER_NETWORK_PREFIX}.0" gw "${BASEBOX_IP}" netmask 255.255.255.0
      sudo route add -net "${BASEBOX_LXD_NETWORK_PREFIX}.0"    gw "${BASEBOX_IP}" netmask 255.255.255.0
      ;;
  esac

  vagrant ssh -- sudo route add -net "${BASEBOX_DOCKER_NETWORK_PREFIX}.0" netmask 255.255.255.0 gw $(limbo lxc info docker | egrep 'eth0:\tinet\t' | awk '{print $3}')
}

limbo_update
