#!/usr/bin/env bash

function limbo_update {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  set -x

  case "$(uname -s)" in
    Darwin) runmany 'sudo route add -net "$1" "${BASEBOX_IP}" 255.255.255.0' "${BASEBOX_NETWORK_PREFIX}"{0..9} ;;
    Linux) runmany 'sudo route add -net "$1" gw "${BASEBOX_IP}" netmask 255.255.255.0' "${BASEBOX_NETWORK_PREFIX}"{0..9} ;;
  esac
}

limbo_update
