#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"

  export BASEBOX_SOURCE="$(limbo id)"
  $cmd_basebox build "$basebox_type" "$nm_export" "$@"
  limbo destroy -f
  $cmd_basebox remove -f 2>&- || true
  $cmd_basebox add

  rm -f "$shome/cidata/meta-data"
  (cd $shome && make)
}

source sub-chain "$BASH_SOURCE" "$@"

