#!/usr/bin/env bash

source normalize

export VAGRANT_CWD="$shome${BASEBOX_INSTANCE:+/instance/${BASEBOX_INSTANCE}}"

local basebox_type=
case "${VAGRANT_DEFAULT_PROVIDER:-}" in
  vmware*)    basebox_type='vmx' ;;
  virtualbox) basebox_type='ovf' ;;
  parallels)  basebox_type='pvm' ;;
  docker)     
    if [[ -n "${BASEBOX_INSTANCE:-}" ]]; then
      VAGRANT_CWD="$shome/instance/${BASEBOX_INSTANCE}-${VAGRANT_DEFAULT_PROVIDER}"
    fi
    ;;
esac


if [[ "$VAGRANT_CWD" != "$shome" ]]; then
  mkdir -p "$VAGRANT_CWD/cidata"
  ln -nfs "$shome/Vagrantfile" "$VAGRANT_CWD/"
  ln -nfs "$shome/script" "$VAGRANT_CWD/"
  ln -nfs "$shome/.ssh" "$VAGRANT_CWD/"
  ln -nfs "../../Makefile" "$VAGRANT_CWD/"
  ln -nfs "../../../cidata/user-data.template" "$VAGRANT_CWD/cdata/"
fi 
