#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  limbo "${1:-provision}"
  limbo reuse
}

source sub-chain "$BASH_SOURCE" "$@"

