#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

   cat "$(set +f; ls -td "$VAGRANT_CWD/.vagrant/machines/default"/*/id | head -1)"; echo
}

source sub-chain "$BASH_SOURCE" "$@"

