#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  vagrant destroy -f || true
  limbo build "$@"
}

source sub-chain "$BASH_SOURCE" "$@"

