#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  exec "${BASEBOX_INSTANCE}" docker run --rm -ti -u ubuntu -w /home/ubuntu "$@" bash -il
}

source sub "$BASH_SOURCE" "$@"
