#!/usr/bin/env bash

function source_id {
  aws ec2 describe-images --filter Name=name,Values="${BASEBOX_NAME}-vagrant-$(aws configure get region)"'-*' --owners self \
    | jq -r '.Images | sort_by(.CreationDate)[] | select(.State != "failed") | .ImageId' \
    | tail -1
}

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"
  if [[ -n "$nm_export" ]]; then
    shift
  fi

  export BASEBOX_SOURCE="$(source_id)"

  basebox build "$@"
  vagrant destroy -f
  basebox remove || true
  basebox add
}

source sub-chain "$BASH_SOURCE" "$@"

