#!/usr/bin/env bash

function limbo_docker {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  export VAGRANT_DEFAULT_PROVIDER='docker'

  eval $(docker machine env --no-proxy $BASEBOX_INSTANCE)

  exec docker "$@"
  #exec limbo "$@"
}

limbo_docker "$@"
