#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  vagrant up --no-provision
  case "$VAGRANT_DEFAULT_PROVIDER" in
    aws)
      limbo sync
      ;;
  esac
  if [[ "$#" == 0 ]]; then
    set -- provision
  fi

  vagrant "$@"
}

source sub-chain "$BASH_SOURCE" "$@"

