#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  vagrant halt
}

source sub "$BASH_SOURCE" "$@"

