#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  exec limbo docker create --swarm-master "$@"
}

source sub "$BASH_SOURCE" "$@"
