#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  export VAGRANT_DEFAULT_PROVIDER='aws'

  box_main "$@"
}

source sub "$BASH_SOURCE" "$@"
