#!/usr/bin/env bash

function limbo_media_add {
  basebox remove || true
  basebox add
}

function limbo_media_prep {
  env LIMBO_FAKE=1 vagrant destroy -f
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"
  if [[ -n "$nm_export" ]]; then
    shift
  fi

  limbo_media_prep
  set -- "$nm_export" "$@"
  basebox build "$@"
  limbo_media_add
}

source sub "$BASH_SOURCE" "$@"
