#!/usr/bin/env bash

function limbo_docker {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  set -x

  export VAGRANT_DEFAULT_PROVIDER='aws'
  exec limbo "$@"
}

limbo_docker "$@"
