#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  case "${1:-}" in
    *:*)
      exec "${BASEBOX_INSTANCE}" docker run --rm -ti -u ubuntu -w /home/ubuntu "$@"
      ;;
    *)
      exec "${BASEBOX_INSTANCE}" docker run --rm -ti -u ubuntu -w /home/ubuntu "${BASEBOX_NAME}:vagrant" "$@"
      ;;
  esac
}

source sub "$BASH_SOURCE" "$@"
