#!/usr/bin/env bash

function source_id {
  echo "${BASEBOX_NAME}:vagrant"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"
  if [[ -n "$nm_export" ]]; then
    shift
  fi

  export BASEBOX_SOURCE="$(source_id)"
  export BASEBOX_TAG="vagrant"
  basebox build "$@"
  mkdir -p "${CACHE_DIR}/box/${VAGRANT_DEFAULT_PROVIDER}"
  docker save -o "${CACHE_DIR}/box/${VAGRANT_DEFAULT_PROVIDER}/${BASEBOX_NAME}${nm_suffix}.docker" "$BASEBOX_SOURCE"
}

source sub-chain "$BASH_SOURCE" "$@"

