#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  exec docker machine "$@" "$BASEBOX_INSTANCE"
}

source sub "$BASH_SOURCE" "$@"
