#!/usr/bin/env bash

function limbo_docker {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  export VAGRANT_DEFAULT_PROVIDER='parallels'

  exec limbo "$@"
}

limbo_docker "$@"
