#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  limbo export "$@"
  case "${1:-}" in
    aws)
      limbo vagrant destroy -f
      ;;
  esac
  limbo repackage "$@"
}

source sub-chain "$BASH_SOURCE" "$@"

