#!/usr/bin/env bash

function limbo_update {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  set -x

  case "$(uname -s)" in
    Darwin) 
      runmany 'sudo route add -net "${1}.0/24" "${BASEBOX_IP}" || true' "${BASEBOX_NETWORK_PREFIX}"{0,9}
      runmany 'sudo route add -net "250.${1}.0/16" "${BASEBOX_IP}" || true' "${BASEBOX_NETWORK_PREFIX##*.}"{0,9}
      ;;
    Linux) runmany 'sudo ip route replace "${1}.0/24" via "${BASEBOX_IP}"' "${BASEBOX_NETWORK_PREFIX}"{0,9}} ;;
  esac
}

limbo_update
