#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local id_ami="$(aws ec2 create-image --name "block-vagrant-$(aws configure get region)-$(hostname -s)-$(date +%s)" --description "vagrant export" --instance-id "${AWS_INSTANCE:-$(limbo id)}" --no-reboot | jq -r '.ImageId')"
  while true; do 
    local state="$(aws ec2 describe-images --image-id "$id_ami" | jq -r '.Images[].State')"
    case "$state" in
      available)
        if [[ -n "${GOLDEN_NAME:-}" ]]; then
          aws ec2 create-tags --resource "$id_ami" --tags Key=Block,Value="$GOLDEN_NAME-$(date +%s)"
        fi
        if [[ -n "${LIMBO_EXPORT:-}" ]]; then
          echo "$id_ami" > "${LIMBO_EXPORT}"
        fi
        break
        ;;
      pending)
        echo "INFO: waiting for ami $id_ami... $(date)"
        sleep 15
        continue
        ;;
      *)
        echo "ERROR: unknown state '$state' while waiting for ami $id_ami" 1>&2
        return 1
        ;;
    esac
  done
}

source sub "$BASH_SOURCE" "$@"

