#!/usr/bin/env bash

function limbo_media_add {
  basebox remove || true
  basebox add
}

function limbo_media_prep {
  vagrant destroy -f
  (set +f; rm -f "${CACHE_DIR}/box/${VAGRANT_DEFAULT_PROVIDER}/${BASEBOX_NAME}${nm_suffix}.ovf" ${CACHE_DIR}/box/${VAGRANT_DEFAULT_PROVIDER}/${BASEBOX_NAME}${nm_suffix}-disk*.vmdk)
}

function source_id {
  echo "${CACHE_DIR}/box/${VAGRANT_DEFAULT_PROVIDER}/${BASEBOX_NAME}${nm_suffix}.ovf"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"
  if [[ -n "$nm_export" ]]; then
    shift
  fi

  export BASEBOX_SOURCE="$(source_id)"

  set -- "$basebox_type" "$nm_export" "$@"
  basebox build "$@"
  limbo_media_prep
  limbo_media_add
}

source sub "$BASH_SOURCE" "$@"
