#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  limbo up --no-provision "$@"
  case "$VAGRANT_DEFAULT_PROVIDER" in
    aws)
      limbo sync
      ;;
  esac
  limbo provision
}

source sub-chain "$BASH_SOURCE" "$@"

