#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  export LIMBO_EXPORT="$(mktemp -t XXXXXX)"
  limbo export "$@"
  limbo vagrant destroy -f
  limbo repackage "$@"
}

source sub-chain "$BASH_SOURCE" "$@"

