#!/usr/bin/env bash

function source_id {
  aws ec2 describe-images --filter Name=name,Values="block-vagrant-$(aws configure get region)"'-*' --owners self \
    | jq -r '.Images | sort_by(.CreationDate)[] | select(.State != "failed") | .ImageId' \
    | tail -1
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local nm_export="${1:-}"
  local nm_suffix="${nm_export:+-${nm_export}}"
  if [[ -n "$nm_export" ]]; then
    shift
  fi

  if [[ -n "${LIMBO_EXPORT:-}" ]]; then
    AMI_SOURCE="$(cat "${LIMBO_EXPORT}")"
    FOGG_AMI="${AMI_SOURCE}"
  fi

  export BASEBOX_SOURCE="${AMI_SOURCE:-$(source_id)}"

  set -- aws "$nm_export" "$@"
  basebox build "$@"
  vagrant destroy -f >/dev/null 2>&1 || true
}

source sub-chain "$BASH_SOURCE" "$@"
