#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  limbo media packer
  env BASEBOX_SOURCE="${BASEBOX_NAME}:packer" limbo build "$@"
}

source sub-chain "$BASH_SOURCE" "$@"

