#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  export CONSUL_SERVER="$BASEBOX_IP"
  limbo swarm --swarm-master "$@"
  limbo docker network create -d overlay inception
}

source sub "$BASH_SOURCE" "$@"
