#!/usr/bin/env bash

function box_main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export VAGRANT_CWD="$shome"

  if [[ "$#" == 0 ]]; then
    echo "$(basename "$0"): up|destroy ssh|rsync|scp id media build export rebuild"
    return 0
  fi

  local nm_action="$1"; shift
  local nm_guest=
  local cmd_guest=
  local nm_rebuilder=

  local nm_basebox_build=
  local basebox_type=

  case "$VAGRANT_DEFAULT_PROVIDER" in
    vmware_fusion)
      nm_guest='osx'
      cmd_guest="${BOX_NAME} osx"
      nm_rebuilder='vmware'
      nm_basebox_build='osx'
      basebox_type='vmx'
      ;;
    virtualbox)
      nm_guest="${BOX_NAME}"
      cmd_guest="${BOX_NAME}"
      nm_rebuilder='virtualbox'
      nm_basebox_build='ubuntu'
      basebox_type='ovf'
      ;;
    aws)
      nm_guest="$AWS_DEFAULT_PROFILE"
      cmd_guest="$nm_guest"
      nm_rebuilder="aws"
      ;;
    docker)
      nm_guest="$(basename "$0")"
      if [[ "$nm_guest" == "${BOX_NAME}0" ]]; then
        cmd_guest="${BOX_NAME} docker"
      else
        cmd_guest="$nm_guest"
      fi
      nm_rebuilder='docker'
      case "$(uname -s)" in
        Darwin)
          local opt_interactive=
          case "$nm_action" in
            ssh)
              opt_interactive="-t"
              ;;
          esac
          ${BOX_NAME} ssh ${opt_interactive:-} "source .bash_profile; require; exec env VAGRANT_DEFAULT_PROVIDER=$VAGRANT_DEFAULT_PROVIDER http_proxy=$http_proxy https_proxy=$https_proxy ssh_gateway=${ssh_gateway:-} ssh_gateway_user=${ssh_gateway_user:=${USER:-${LOGNAME}}} $nm_guest $nm_action $*"
          return $?
          ;;
      esac
      ;;
    *)
      echo "ERROR: unknown provider $VAGRANT_DEFAULT_PROVIDER" 1>&2
      return 1
      ;;
  esac

  case "$nm_action" in
    media)
      case "$nm_rebuilder" in
        virtualbox|vmware)
          $cmd_guest destroy -f
          $nm_rebuilder build "$nm_basebox_build"
          $nm_rebuilder remove 2>&- || true
          $nm_rebuilder add
          ;;
        aws)
          $cmd_guest destroy -f
          $nm_rebuilder build "$AWS_DEFAULT_PROFILE"
          $nm_rebuilder remove "$AWS_DEFAULT_PROFILE" 2>&- || true
          $nm_rebuilder add "$AWS_DEFAULT_PROFILE"
          ;;
        docker)
          if [[ "$nm_guest" == "${BOX_NAME}0" ]]; then
            export BASEBOX_SOURCE="ubuntu:trusty"
            export BASEBOX_TAG="packer"
            $nm_rebuilder build "$BASEBOX_SOURCE"
          else
            export BASEBOX_TAG="vagrant"
            docker commit "$(${BOX_NAME}0 id)" "${BASEBOX_NAME}:${BASEBOX_TAG}"
          fi
          ;;
      esac
      ;;
    export)
      local nm_export="${1:-}"
      local nm_suffix="${nm_export:+-${nm_export}}"
      case "$nm_rebuilder" in
        virtualbox)
          cat "${shome}/.ssh/ssh-vagrant.pub" | $cmd_guest ssh tee -a '~ubuntu/.ssh/authorized_keys'
          $cmd_guest ssh sudo rm -rf /dev/.udev
          $cmd_guest ssh sudo rm -f /lib/udev/rules.d/75-persistent-net-generator.rules
          $cmd_guest ssh sudo rm -rf /var/lib/dhcp # TODO assumes only leases are here
          $cmd_guest ssh sudo mkdir -p /var/lib/dhcp
          $cmd_guest halt

          (set +f; rm -f "${BASEBOX_CACHE}/box/${BASEBOX_NAME}${nm_suffix}.ovf" ${BASEBOX_CACHE}/box/${BASEBOX_NAME}${nm_suffix}-disk*.vmdk)
          (set -x; VBoxManage export $($cmd_guest id) --ovf20 -o "${BASEBOX_CACHE}/box/${BASEBOX_NAME}${nm_suffix}.ovf")
          ;;
        vmware)
          $cmd_guest halt
          ;;
        docker)
          if [[ "$nm_guest" == "${BOX_NAME}0" ]]; then
            docker commit "$($cmd_guest id)" "${BASEBOX_NAME}:vagrant"
          fi
          ;;
      esac
      ;;
    import)
      local nm_import="${1:-}"
      local nm_suffix="${nm_import:+-${nm_import}}"
      case "$nm_rebuilder" in
        docker)
          docker load -i "${BASEBOX_CACHE}/box/${BASEBOX_NAME}.docker"
          ;;
        virtualbox)
          $nm_rebuilder remove 2>&- || true
          $nm_rebuilder add
          ;;
      esac
      ;;
    rebuild)
      local nm_export="${1:-}"
      local nm_suffix="${nm_export:+-${nm_export}}"
      case "$nm_rebuilder" in
        virtualbox|vmware)
          case "$nm_rebuilder" in
            vmware)
              export BASEBOX_SOURCE="$($cmd_guest id)"
              ;;
            virtualbox)
              export BASEBOX_SOURCE="${BASEBOX_CACHE}/box/${BASEBOX_NAME}${nm_suffix}.ovf"
              ;;
          esac

          $nm_rebuilder build "$nm_basebox_build" "$basebox_type" "$nm_export" "$@"
          $cmd_guest destroy -f
          $nm_rebuilder remove 2>&- || true
          $nm_rebuilder add

          rm -f "$shome/cidata/meta-data"
          (cd $shome && make)
          ;;
        docker)
          export BASEBOX_SOURCE="${BASEBOX_NAME}:vagrant"
          if [[ "$nm_guest" == "${BOX_NAME}0" ]]; then
            export BASEBOX_TAG="vagrant"
            $nm_rebuilder build
            docker images -a
            docker history "$BASEBOX_SOURCE" || true
            docker save -o "${BASEBOX_CACHE}/box/${BASEBOX_NAME}${nm_suffix}.docker" "$BASEBOX_SOURCE"
            docker history "$BASEBOX_SOURCE"
          fi
          ;;
      esac
      $cmd_guest destroy -f
      exec $cmd_guest up
      ;;
    up)
      exec parity "$nm_action" "$nm_guest" "$@"
      ;;
    destroy)
      exec vagrant "$nm_action" "$nm_guest" "$@"
      ;;
    ssh|rsync|scp)
      exec parity "$nm_action" "$nm_guest" "$@"
      ;;
    id)
      cat "$(set +f; ls -td "$VAGRANT_CWD/.vagrant/machines/$nm_guest"/*/id | head -1)"; echo
      ;;
    build)
      exec $cmd_guest up
      ;;
    box*)
      exec "$nm_action" "$@"
      ;;
    remote)
      local quoted=()
      while [[ "$#" -gt 0 ]]; do
        if [[ -n "$1" ]]; then
          quoted+=($(printf '%q' "$1"))
        else
          quoted+=("''")
        fi
        shift
      done
      exec parity ssh "$nm_guest" "${quoted[@]}"
      ;;
    *)
      exec vagrant "$nm_action" "$nm_guest" "$@"
      ;;
  esac
}
