#!/usr/bin/env bash

function limbo_update {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      if netstat -rn | grep "${BASEBOX_DOCKER_NETWORK_PREFIX}/.*${BASEBOX_IP}"; then
        sudo route delete -net "${BASEBOX_DOCKER_NETWORK_PREFIX}.0" "${BASEBOX_IP}" 255.255.255.0 2>&- || true
        sudo route delete -net "${BASEBOX_DOCKER_NETWORK_PREFIX}" "${BASEBOX_IP}" 255.255.255.0 2>&- || true
      fi
      sudo route add -net "${BASEBOX_DOCKER_NETWORK_PREFIX}.0" "${BASEBOX_IP}" 255.255.255.0

      if netstat -rn | grep "${BASEBOX_LXD_NETWORK_PREFIX}/.*${BASEBOX_IP}"; then
        sudo route delete -net "${BASEBOX_LXD_NETWORK_PREFIX}.0" "${BASEBOX_IP}" 255.255.255.0 2>&- || true
        sudo route delete -net "${BASEBOX_LXD_NETWORK_PREFIX}" "${BASEBOX_IP}" 255.255.255.0 2>&- || true
      fi
      sudo route add -net "${BASEBOX_LXD_NETWORK_PREFIX}.0" "${BASEBOX_IP}" 255.255.255.0
      ;;
    Linux)
      sudo route add -net "${BASEBOX_DOCKER_NETWORK_PREFIX}.0" gw "${BASEBOX_IP}" netmask 255.255.255.0
      sudo route add -net "${BASEBOX_LXD_NETWORK_PREFIX}.0" gw "${BASEBOX_IP}" netmask 255.255.255.0
      ;;
  esac
}

limbo_update
