#!/usr/bin/env bash

function limbo_media_add {
  docker save -o "${CACHE_DIR}/box/${BASEBOX_NAME}-${BASEBOX_TAG}.docker" "$BASEBOX_NAME:$BASEBOX_TAG"
}

function limbo_media_prep {
  export BASEBOX_SOURCE="ubuntu:trusty"
  export BASEBOX_TAG="packer"
  set -- "$BASEBOX_SOURCE" "$@"
}

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  limbo_media_prep
  basebox build "$@"
  limbo_media_add
}

source sub "$BASH_SOURCE" "$@"
