#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  vagrant destroy -f 2>&- || true
  limbo build "$@"
}

source sub-chain "$BASH_SOURCE" "$@"

