#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  local quoted=()
  while [[ "$#" -gt 0 ]]; do
    if [[ -n "$1" ]]; then
      quoted+=($(printf '%q' "$1"))
    else
      quoted+=("''")
    fi
    shift
  done
  exec parity ssh "$BASEBOX_NAME" "${quoted[@]}"
}

source sub-chain "$BASH_SOURCE" "$@"

