#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- "${BASEBOX_NAME}:vagrant"
  fi

  exec "${BASEBOX_INSTANCE}" docker run --rm -ti -u ubuntu -w /home/ubuntu "$@" bash -il
}

source sub "$BASH_SOURCE" "$@"
