#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source limbo_common

  if [[ -n "${1:-}" ]]; then
    shift 
  fi
  vagrant up --no-provision
  vagrant provision
}

source sub-chain "$BASH_SOURCE" "$@"

