#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  set -x
  vagrant halt
  prlctl stop "$(limbo id)" || true
  prlctl unregister "$(limbo id)" || true
}

source sub "$BASH_SOURCE" "$@"

