#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  exec "$BASEBOX_INSTANCE" docker run -d -p 8500:8500 -h consul progrium/consul -server -bootstrap
}

source sub "$BASH_SOURCE" "$@"
