#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source limbo_common

  env LIMBO_FAKE=1 limbo destroy -f
  $cmd_basebox build
  $cmd_basebox remove -f 2>&- || true
  $cmd_basebox add
}

source sub-chain "$BASH_SOURCE" "$@"

