#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure security/mozilla-rootcerts
  mozilla-rootcerts install || true

  pkg ensure misc/getopt
  pkg ensure net/wget
  pkg ensure www/curl
  pkg ensure devel/jq
  pkg ensure misc/tmux
  pkg ensure editors/vim
  pkg ensure devel/git
}

bootstrap

