#!/usr/bin/env bash

function main {
  local net_bridge="$1"; shift

  sudo install -d /vagrant
  sudo install -d /vagrant/packages
  sudo chown -R ubuntu:ubuntu /vagrant/.
  find /vagrant/. -type d -print0 | xargs -0 -n 1000 sudo chmod g+s
}

main "$@"
