#!/usr/bin/env bash

function docker_stuff {
  if ! docker pull ubuntu >/dev/null 2>&1; then
    return
  fi

  # configure routing
  echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward  
  echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.d/60-ip-forward.conf
}

function git_stuff {
  # initialize new ssh hosts
  rm -f ~/.ssh/known_hosts
  ssh -oStrictHostKeyChecking=no github.com true &
  ssh -oStrictHostKeyChecking=no bitbucket.org true &
  ssh -oStrictHostKeyChecking=no localhost true &
  wait
}

function home_stuff {
  local git_home="$1"; shift

  # clone home
  if [[ ! -d .git ]]; then
    git clone "$git_home" home
    mv home/.git . || rm -rf home/.git
  fi
  
  git reset --hard
  git clean -fd
  git pull

  set +x; 
  source script/ciprofile
  set -x
}

function app_stuff {
  # bootstrap app
  git clone git@github.com:defn/block work/block || true
  pushd work/block
  git pull
  script/bootstrap
  set +x; source script/profile; require; set -x
  popd
}

function cache_stuff {
  export BASEBOX_CACHE="/vagrant"

  if [[ ! -d "$BASEBOX_CACHE" ]]; then
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/cache"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/box"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/distfiles"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/packages"
  fi

  {
    echo "Acquire::Languages { \"en\"; };"
    echo "Acquire::http { Pipeline-Depth \"200\"; }"
  } | sudo tee /etc/apt/apt.conf.d/99boxcache

  if [[ -n "${http_proxy:-}" ]]; then
    export http_proxy
    export https_proxy="$http_proxy"
    export ftp_proxy="$http_proxy"

    {
      echo "Acquire::http::Proxy \"$http_proxy\";"
    } | sudo tee -a /etc/apt/apt.conf.d/99boxcache
  fi
}

function update_stuff {
  case "$(uname -s)" in
    Darwin)
      #sudo softwareupdate -i -v -a
      ;;
    Linux)
      sudo aptitude update > /dev/null
      sudo aptitude upgrade -y
      ;;
  esac
}

function clean_stuff {
  sudo rm -f /etc/apt/apt.conf.d/99boxcache
}

function fully_source {
  set +x; require; set -x
}

function main {
  # setup
  set -x; cd
  local nm_repo="$1"; shift
  if [[ -n "${1:-}" ]]; then
    http_proxy="$1"; shift
  fi

  sudo aptitude -y install git vim unzip curl language-pack-en # mirror basebox-ubuntu/site.sh

  # setup
  cache_stuff
  git_stuff
  home_stuff "$nm_repo"
  app_stuff

  # bootstrap dependencies
  app clone
  app runmany 8 'cd $1 && git pull' || true
  app clone
  app bootstrap

  # fully source home
  fully_source

  # bootstrap docker
  docker_stuff

  # update packages
  update_stuff

  # cleanup
  clean_stuff
}

exec 2>&1
main "$@" | tee -a cibuild.log
