#!/usr/bin/env bash

function main {
  # start docker
  sudo service docker start
  sleep 5

  # load ubuntu:vagrant image
  time docker load -i /vagrant/box/vagrant.docker

  # bring up box1
  box1 up
  box1 ssh uname -a
}

set -exfu
exec 2>&1
cd
main "$@" | tee -a cibuild.log
