#!/usr/bin/env bash

function main {
  local net_bridge="$1"; shift

  if sudo lvs system/docker-data; then
    if ! sudo lvs system/docker-data | awk 'NR == 2 { print $3 }' | grep ^t; then
      sudo lvremove -f system/docker-data 2>&- >/dev/null || true
      sudo lvcreate -T -L 30G --poolmetadatasize 4G system/docker-data
    fi
  fi

	sudo lvdisplay -m system
  lsblk

  local nm_driver="$(sudo docker info 2>&- | awk '/Storage Drive/ { print $3 }')"
  if [[ "$nm_driver" != "overlay" ]]; then
    sudo service docker stop 2>&- || true
    sudo usermod -aG docker ubuntu
    sudo rm -rf /var/lib/docker 
    cat << ____EOF | sudo tee /etc/default/docker
    DOCKER_OPTS='
    -H tcp://0.0.0.0:2376
    -H unix:///var/run/docker.sock
    --storage-driver overlay
    '
____EOF
  fi
}

main "$@"
