#!/usr/bin/env bash

function main {
  local net_bridge="$1"; shift

	if ! grep -s /etc/network/interfaces.d /etc/network/interfaces; then
    {
      echo
      echo 'source-directory /etc/network/interfaces.d'
    } | sudo tee -a /etc/network/interfaces
	fi

  cat | sudo tee -a "/etc/network/interfaces.d/br0" <<__EOF
auto
iface br0 inet static
  address "${net_bridge}.0"
  netmask "255.255.255.0"
  pre-up brctl addbr br0
  post-down brctl delbr br0
__EOF

  sudo ifup br0 || true

  if sudo lvs system/docker-data; then
    if ! sudo lvs system/docker-data | awk 'NR == 2 { print $3 }' | grep ^t; then
      sudo lvremove -f system/docker-data || true
      sudo lvcreate -T -L 30G --poolmetadatasize 4G system/docker-data
    fi
  fi

	sudo lvs
  lsblk
}

main "$@"
