#!/usr/bin/env bash

function main {
  local net_bridge="$1"; shift
  local cache_vip="$1"; shift

  set -x
  service lxd stop 2>/dev/null || true
  rm -rf /var/lib/lxd
  mkdir -p /var/lib/lxd
  mount -o user_subvol_rm_allowed /dev/system/lxd /var/lib/lxd

  cat <<EOF | tee /etc/default/lxd-bridge
USE_LXD_BRIDGE="true"
LXD_BRIDGE="lxdbr0"
UPDATE_PROFILE="true"
LXD_CONFILE=""
LXD_DOMAIN="lxd"
LXD_IPV4_ADDR="${net_bridge}.1"
LXD_IPV4_NETMASK="255.255.255.0"
LXD_IPV4_NETWORK="${net_bridge}.1/24"
LXD_IPV4_DHCP_RANGE="${net_bridge}.10,${net_bridge}.200"
LXD_IPV4_DHCP_MAX="191"
LXD_IPV4_NAT="true"
LXD_IPV6_ADDR=""
LXD_IPV6_MASK=""
LXD_IPV6_NETWORK=""
LXD_IPV6_NAT="false"
LXD_IPV6_PROXY="false"
EOF

  service lxd start

  lxc config set core.https_address [::]
  lxc config set core.trust_password ubuntu

  chown -R ubuntu:ubuntu ~ubuntu/.config
}

main "$@"
