#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$(type -P tmux)" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
