#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  if "$shome/script/stale"; then
    "$shome/script/bootstrap"
  fi

  if ! VBoxManage list hostonlyifs | grep vboxnet0; then
    VBoxManage hostonlyif create
  fi
  VBoxManage hostonlyif ipconfig vboxnet0 --ip 172.28.128.1 --netmask 255.255.255.0

  cat "$shome/etc/squid.conf.template" | envsubst '${BASEBOX_CACHE}' > "$shome/etc/squid.conf"
  mkdir -p "${BASEBOX_CACHE}/cache/squid"
  squid -f "$shome/etc/squid.conf" -zN
  block compile service

  make

  case "$(uname -s)" in
    Darwin)
      if ! netstat -rn | grep '172.17[ ]*172.28.128.3'; then
        sudo route add -net 172.17.0.0 172.28.128.3 255.255.0.0
      fi
      ;;
  esac
}

bootstrap

