#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  if "$shome/script/stale"; then
    "$shome/script/bootstrap"
  fi

  if ! VBoxManage list hostonlyifs | grep vboxnet0; then
    VBoxManage hostonlyif create
  fi
  VBoxManage hostonlyif ipconfig vboxnet0 --ip 172.28.128.1 --netmask 255.255.255.0

  block compile service
}

bootstrap

